version: "3.8"
services:


  php:
    build:
      context: .
      target: php #as specified at top of dockerfile
      args:
        - APP_ENV=${APP_ENV}
    environment: 
      - APP_ENV=${APP_ENV}
      - CONTAINER_ROLE=app
    working_dir: /var/www
    volumes: 
      - ./:/var/www
    ports:
      - 8000:8000
    depends_on:
      - database
      - redis

  database:
    image: mysql:8.0
    ports:
      - 3306:3306 
    volumes: 
      - db-data:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=${DB_DATABASE}
      - MYSQL_USER=${DB_USERNAME}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
  
  redis:
    image: redis:alpine
    ports:
      - 6379:6379
    command: redis-server --appendonly yes --requirepass "${REDIS_PASSWORD}"

volumes:
  db-data: ~
      
